from __future__ import annotations

import json
from collections.abc import Callable
from dataclasses import replace
from pathlib import Path
from typing import Any, Protocol

from orchestra_agent.domain.enums import BackupScope, RiskLevel
from orchestra_agent.domain.serialization import step_plan_to_dict, workflow_to_dict
from orchestra_agent.domain.step import Step
from orchestra_agent.domain.step_plan import StepPlan
from orchestra_agent.domain.workflow import Workflow
from orchestra_agent.ports.llm_client import (
    ILlmClient,
    LlmAttachment,
    LlmGenerateRequest,
    LlmMessage,
)
from orchestra_agent.ports.planner import IPlanner
from orchestra_agent.shared.error_handling import text_preview


class IStepProposalProvider(Protocol):
    def propose(self, workflow: Workflow, draft_plan: StepPlan) -> dict[str, Any] | None:
        ...


class JsonFileStepProposalProvider(IStepProposalProvider):
    """
    Reads a proposal JSON file generated by an external LLM process.
    """

    def __init__(self, proposal_file: Path) -> None:
        self._proposal_file = proposal_file

    def propose(self, workflow: Workflow, draft_plan: StepPlan) -> dict[str, Any] | None:
        if not self._proposal_file.is_file():
            return None
        content = self._proposal_file.read_text(encoding="utf-8")
        parsed = json.loads(content)
        if not isinstance(parsed, dict):
            return None
        return parsed


class LlmStepProposalProvider(IStepProposalProvider):
    """
    Generates step patches from a live LLM client.
    """

    def __init__(
        self,
        llm_client: ILlmClient,
        temperature: float = 0.0,
        max_tokens: int = 1200,
    ) -> None:
        self._llm_client = llm_client
        self._temperature = temperature
        self._max_tokens = max_tokens

    def propose(self, workflow: Workflow, draft_plan: StepPlan) -> dict[str, Any] | None:
        system_prompt = (
            "You are a workflow plan patch generator for Excel automation.\n"
            "Return ONLY a JSON object with this exact top-level shape:\n"
            '{"steps":[{"step_id":"...", "field":"value"}]}\n'
            "Rules:\n"
            "1) Patch existing step_id only.\n"
            "2) Do NOT add or remove steps.\n"
            "3) Keep tool_ref within Excel tools only.\n"
            "4) When workflow.replan_context is present, use source_workflow_document and "
            "change_summary as the authoritative replan input.\n"
            "5) Respect workflow.feedback_history as the latest correction intent.\n"
            "6) Keep output minimal and valid JSON."
        )
        draft_payload = {
            "workflow": workflow_to_dict(workflow),
            "draft_step_plan": step_plan_to_dict(draft_plan),
        }
        user_prompt = json.dumps(draft_payload, ensure_ascii=False, indent=2)

        request = LlmGenerateRequest(
            messages=(
                LlmMessage(role="system", content=system_prompt),
                LlmMessage(
                    role="user",
                    content=user_prompt,
                    attachments=self._workflow_attachments(workflow),
                ),
            ),
            response_format="json_object",
            temperature=self._temperature,
            max_tokens=self._max_tokens,
        )
        raw = self._llm_client.generate(request)
        parsed = self._extract_json(raw)
        if not isinstance(parsed, dict):
            raise ValueError("LLM proposal must be a JSON object.")
        return parsed

    @staticmethod
    def _extract_json(raw_text: str) -> Any:
        stripped = raw_text.strip()
        try:
            return json.loads(stripped)
        except json.JSONDecodeError:
            pass

        start = stripped.find("{")
        end = stripped.rfind("}")
        if start == -1 or end == -1 or end <= start:
            preview = text_preview(stripped)
            raise ValueError(f"LLM proposal is not valid JSON. preview={preview}")

        candidate = stripped[start : end + 1]
        return json.loads(candidate)

    @staticmethod
    def _workflow_attachments(workflow: Workflow) -> tuple[LlmAttachment, ...]:
        return tuple(LlmAttachment(path=file_path) for file_path in workflow.reference_files)


class SafeAugmentedLlmPlanner(IPlanner):
    """
    Safe planner wrapper:
    1) Build deterministic draft plan.
    2) Optionally apply constrained LLM step patches.
    3) Validate final plan invariants (DAG, IDs, enums).
    If any rule fails, fallback to deterministic draft.
    """

    _allowed_tool_refs = {
        "excel.create_file",
        "excel.open_file",
        "excel.read_sheet",
        "excel.calculate_sum",
        "excel.create_sheet",
        "excel.write_cells",
        "excel.save_file",
    }

    def __init__(
        self,
        base_planner: IPlanner,
        proposal_provider: IStepProposalProvider | None = None,
    ) -> None:
        self._base_planner = base_planner
        self._proposal_provider = proposal_provider
        self.last_warning: str | None = None

    def compile_step_plan(self, workflow: Workflow) -> StepPlan:
        self.last_warning = None
        draft = self._base_planner.compile_step_plan(workflow)
        if self._proposal_provider is None:
            return draft

        proposal = self._proposal_provider.propose(workflow, draft)
        if proposal is None:
            return draft

        try:
            return self._apply_proposal(draft, proposal)
        except Exception as exc:  # noqa: BLE001
            self.last_warning = f"LLM proposal rejected; fallback applied: {exc}"
            return draft

    def _apply_proposal(self, draft: StepPlan, proposal: dict[str, Any]) -> StepPlan:
        raw_steps = proposal.get("steps")
        if not isinstance(raw_steps, list):
            raise ValueError("Proposal must contain a 'steps' list.")

        updated = {step.step_id: step for step in draft.steps}
        for patch in raw_steps:
            if not isinstance(patch, dict):
                raise ValueError("Each proposal step patch must be an object.")
            step_id = patch.get("step_id")
            if not isinstance(step_id, str):
                raise ValueError("Each step patch must include a string 'step_id'.")
            if step_id not in updated:
                raise ValueError(f"Unknown step_id in proposal: '{step_id}'.")

            source_step = updated[step_id]
            updated[step_id] = self._apply_patch(source_step, patch)

        candidate = StepPlan(
            step_plan_id=draft.step_plan_id,
            workflow_id=draft.workflow_id,
            version=draft.version,
            steps=[updated[step.step_id] for step in draft.steps],
        )
        return candidate

    def _apply_patch(self, source_step: Step, patch: dict[str, Any]) -> Step:
        changes: dict[str, Any] = {}

        self._apply_if_present(patch, "name", changes, lambda value: self._as_str("name", value))
        self._apply_if_present(
            patch,
            "description",
            changes,
            lambda value: self._as_str("description", value),
        )
        if "tool_ref" in patch:
            tool_ref = self._as_str("tool_ref", patch["tool_ref"])
            if tool_ref not in self._allowed_tool_refs:
                raise ValueError(f"tool_ref '{tool_ref}' is not allowed.")
            changes["tool_ref"] = tool_ref

        self._apply_if_present(
            patch,
            "resolved_input",
            changes,
            self._as_dict,
        )
        if "depends_on" in patch:
            changes["depends_on"] = self._as_str_list("depends_on", patch["depends_on"])

        self._apply_if_present(
            patch,
            "risk_level",
            changes,
            lambda value: RiskLevel(self._as_str("risk_level", value)),
        )
        self._apply_if_present(
            patch,
            "requires_approval",
            changes,
            lambda value: self._as_bool("requires_approval", value),
        )
        self._apply_if_present(
            patch,
            "run",
            changes,
            lambda value: self._as_bool("run", value),
        )
        self._apply_if_present(
            patch,
            "skip",
            changes,
            lambda value: self._as_bool("skip", value),
        )
        self._apply_if_present(
            patch,
            "backup_scope",
            changes,
            lambda value: BackupScope(self._as_str("backup_scope", value)),
        )

        return replace(source_step, **changes)

    @staticmethod
    def _as_str(key: str, value: Any) -> str:
        if not isinstance(value, str):
            raise ValueError(f"{key} must be a string.")
        return value

    @staticmethod
    def _as_bool(key: str, value: Any) -> bool:
        if not isinstance(value, bool):
            raise ValueError(f"{key} must be bool.")
        return value

    @staticmethod
    def _as_dict(value: Any) -> dict[str, Any]:
        if not isinstance(value, dict):
            raise ValueError("resolved_input must be an object.")
        return value

    @staticmethod
    def _as_str_list(key: str, value: Any) -> list[str]:
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise ValueError(f"{key} must be a list of strings.")
        return value

    @staticmethod
    def _apply_if_present(
        patch: dict[str, Any],
        key: str,
        changes: dict[str, Any],
        converter: Callable[[Any], Any],
    ) -> None:
        if key not in patch:
            return
        changes[key] = converter(patch[key])
